name = "moosburg-transparent"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages/Workers Assets
[assets]
directory = ".open-next/assets"
binding = "ASSETS"
